// webapp/src/components/ui/ToastContainer.vue
<script setup lang="ts">
import { useToastStore } from '@/stores/toast'
import type { Toast } from '@/types/ui'

const toastStore = useToastStore()

function bgClass(type: Toast['type']): string {
  const map: Record<Toast['type'], string> = {
    success: 'text-bg-success',
    error: 'text-bg-danger',
    warning: 'text-bg-warning',
    info: 'text-bg-info',
  }
  return map[type]
}

function iconClass(type: Toast['type']): string {
  const map: Record<Toast['type'], string> = {
    success: 'bi-check-circle-fill',
    error: 'bi-x-circle-fill',
    warning: 'bi-exclamation-triangle-fill',
    info: 'bi-info-circle-fill',
  }
  return map[type]
}
</script>

<template>
  <div
    class="toast-container position-fixed bottom-0 end-0 p-3"
    style="z-index: 1100"
    aria-live="polite"
  >
    <div
      v-for="toast in toastStore.toasts"
      :key="toast.id"
      class="toast show align-items-center border-0"
      :class="bgClass(toast.type)"
      role="alert"
    >
      <div class="d-flex">
        <div class="toast-body d-flex align-items-center gap-2">
          <i class="bi" :class="iconClass(toast.type)" />
          {{ toast.message }}
        </div>
        <button
          type="button"
          class="btn-close btn-close-white me-2 m-auto"
          aria-label="Close"
          @click="toastStore.dismiss(toast.id)"
        />
      </div>
    </div>
  </div>
</template>

// src/components/ToastContainer.tsx
import { useEffect } from 'react';
import { useNotifications } from '../contexts/NotificationContext';
import type { Notification, NotificationType } from '../types/notification';

const AUTO_DISMISS_DELAY = 5000; // 5 seconds

function getAlertClass(type: NotificationType): string {
  switch (type) {
    case 'success':
      return 'alert-success';
    case 'error':
      return 'alert-error';
    case 'warning':
      return 'alert-warning';
    case 'info':
      return 'alert-info';
    default:
      return '';
  }
}

function ToastItem({ notification, onDismiss }: { notification: Notification; onDismiss: () => void }) {
  useEffect(() => {
    const timer = setTimeout(() => {
      onDismiss();
    }, AUTO_DISMISS_DELAY);

    return () => clearTimeout(timer);
  }, [onDismiss]);

  return (
    <div
      role="alert"
      className={`alert ${getAlertClass(notification.type)} shadow-lg`}
      data-testid={`toast-${notification.id}`}
    >
      <div className="flex-1">
        <span>{notification.message}</span>
      </div>
      <button
        className="btn btn-sm btn-ghost btn-circle"
        onClick={onDismiss}
        aria-label="Dismiss notification"
      >
        ✕
      </button>
    </div>
  );
}

export function ToastContainer() {
  const { notifications, clearNotification } = useNotifications();

  // Only show the 3 most recent unread notifications as toasts
  const toasts = notifications.filter((n) => !n.read).slice(0, 3);

  if (toasts.length === 0) {
    return null;
  }

  return (
    <div className="toast toast-end toast-top z-[9999]" data-testid="toast-container">
      {toasts.map((notification) => (
        <ToastItem
          key={notification.id}
          notification={notification}
          onDismiss={() => clearNotification(notification.id)}
        />
      ))}
    </div>
  );
}
